NETCoreMVCwithMSGraph/Models/CalendarModel.cs
using Microsoft.Graph;

namespace NETCoreMVCwithMSGraph.Models
{
    public class CalendarModel
    {
        public IEnumerable<Event>? Events { get; set; }
        
    }
}

NETCoreMVCwithMSGraph/Models/Email.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Graph;

namespace NETCoreMVCwithMSGraph.Models
{
    public class Email
    {
        [BindProperty(SupportsGet = true)]
        public string NextLink { get; set; }
        public IEnumerable<Message>? Messages { get; set; }
    }
}

NETCoreMVCwithMSGraph/Models/ErrorViewModel.cs
namespace NETCoreMVCwithMSGraph.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NETCoreMVCwithMSGraph/Models/Profile.cs
namespace NETCoreMVCwithMSGraph.Models
{
    public class Profile
    {
        public string? UserDisplayName { get; set; }
        public string? UserPhoto { get; set; }
       
    }
}

NETCoreMVCwithMSGraph/Models/ToDoTaskModel.cs
using Microsoft.Graph;

namespace NETCoreMVCwithMSGraph.Models
{
    public class ToDoTaskModel
    {
      public IEnumerable<TodoTaskList>? TaskLists { get; set; }
    }
}

NETCoreMVCwithMSGraph/Controllers/CalendarController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Graph;
using Microsoft.Identity.Web;
using NETCoreMVCwithMSGraph.Graph;
using NETCoreMVCwithMSGraph.Models;

namespace NETCoreMVCwithMSGraph.Controllers
{
    [AuthorizeForScopes(ScopeKeySection = "DownstreamApi:Scopes")]
    public class CalendarController : Controller
    {
        private readonly ILogger<CalendarController> _logger;
        private readonly CalendarClient _calendarClient;
        private readonly ProfileClient _profileClient;
        private MailboxSettings? MailboxSettings { get; set; }
        public CalendarController(ILogger<CalendarController> logger, CalendarClient calendarClient, ProfileClient profileClient)
        {
            _logger = logger;
            _calendarClient = calendarClient;
            _profileClient = profileClient;
        }
        public async Task<IActionResult> Index()
        {
            CalendarModel calendarModel = new CalendarModel();
            MailboxSettings = await _calendarClient.GetUserMailboxSettings();
            var userTimeZone = (String.IsNullOrEmpty(MailboxSettings.TimeZone))
                                ? "Pacific Standard Time" : MailboxSettings.TimeZone;
            //calendarModel.Events = await _calendarClient.GetEvents(userTimeZone);
            calendarModel.Events = await _calendarClient.GetEventsAsync();
            return View(calendarModel);
        }
        public string FormatDateTimeTimeZone(DateTimeTimeZone value)
        {
            // Parse the date/time string from Graph into a DateTime
            var graphDatetime = value.DateTime;
            if (DateTime.TryParse(graphDatetime, out DateTime dateTime))
            {
                var dateTimeFormat = $"{MailboxSettings.DateFormat} {MailboxSettings.TimeFormat}".Trim();
                if (!String.IsNullOrEmpty(dateTimeFormat))
                {
                    return dateTime.ToString(dateTimeFormat);
                }
                else
                {
                    return $"{dateTime.ToShortDateString()} {dateTime.ToShortTimeString()}";
                }
            }
            else
            {
                return graphDatetime;
            }
        }
    }
}

NETCoreMVCwithMSGraph/Controllers/EmailController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Graph;
using Microsoft.Identity.Web;
using NETCoreMVCwithMSGraph.Graph;
using NETCoreMVCwithMSGraph.Models;
using System.Net.Mail;

namespace NETCoreMVCwithMSGraph.Controllers
{
    [AuthorizeForScopes(ScopeKeySection = "DownstreamApi:Scopes")]
    public class EmailController : Controller
    {
        private readonly EmailClient _emailClient;
        public EmailController(EmailClient emailClient)
        {
            _emailClient=emailClient;
        }
        public async Task<IActionResult> Index()
        {
            Email email = new Email();
            var messagesPagingData = await _emailClient.GetUserMessagesPage(email.NextLink);
            email.Messages = messagesPagingData.Messages;
            email.NextLink = messagesPagingData.NextLink;
            return View(email);
        }
    }
}

NETCoreMVCwithMSGraph/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Web;
using NETCoreMVCwithMSGraph.Graph;
using NETCoreMVCwithMSGraph.Models;
using System.Diagnostics;


namespace NETCoreMVCwithMSGraph.Controllers
{
    [AuthorizeForScopes(ScopeKeySection = "DownstreamApi:Scopes")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ProfileClient _profileClient;
       
        readonly ITokenAcquisition _tokenAcquisition;
        public HomeController(ILogger<HomeController> logger, ProfileClient profileClient, ITokenAcquisition tokenAcquisition)
        {
            _logger = logger;
            _profileClient = profileClient;
            _tokenAcquisition = tokenAcquisition;
        }

        public async Task<IActionResult> Index()
        {
            Profile profile = new Profile();
            var user = await _profileClient.GetUserProfile();
            profile.UserDisplayName = user.DisplayName.Split(' ')[0];
            profile.UserPhoto = await _profileClient.GetUserProfileImage();
            return View(profile);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [AllowAnonymous]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NETCoreMVCwithMSGraph/Controllers/ToDoTaskController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Web;
using NETCoreMVCwithMSGraph.Graph;
using NETCoreMVCwithMSGraph.Models;

namespace NETCoreMVCwithMSGraph.Controllers
{
    [AuthorizeForScopes(ScopeKeySection = "DownstreamApi:Scopes")]
    public class ToDoTaskController : Controller
    {
        private readonly ToDoTaskClient _toDoTaskClient;
        public ToDoTaskController(ToDoTaskClient toDoTaskClient)
        {
            _toDoTaskClient= toDoTaskClient;
        }
        public async Task<IActionResult> Index()
        {
            ToDoTaskModel toDoTaskModel = new ToDoTaskModel();
            var toDoTaskList = await _toDoTaskClient.GetToDoTaskList();
            toDoTaskModel.TaskLists = toDoTaskList;         
            return View(toDoTaskModel);
        }
    }
}

NETCoreMVCwithMSGraph/Views/Calendar/Index.cshtml
@model NETCoreMVCwithMSGraph.Models.CalendarModel
@{
    ViewData["Title"] = "Calendar Events";
}

<div>
    <h1>Calendar Events</h1>
    @if ((User.Identity?.IsAuthenticated == true))
    {
        if (Model.Events != null && Model.Events.Any())
        {
            @foreach (var evt in Model.Events)
            {
                <div class="card" style="width: 50rem;">
                    <div class="card-body">
                        <h5 class="card-title">
                            @evt.Subject
                        </h5>
                        <p class="card-text">
                            <div class="container">
                                <div class="row">
                                    <div class="col-2">
                                        <strong>Start:</strong>
                                    </div>
                                    <div class="col">
                                        @*@Model.FormatDateTimeTimeZone(evt.Start)*@
                                        @evt.Start
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-2">
                                        <strong>End:</strong>
                                    </div>
                                    <div class="col">
                                        @*@Model.FormatDateTimeTimeZone(evt.End)*@
                                        @evt.End
                                    </div>
                                </div>
                            </div>
                        </p>
                    </div>
                </div>
                <br />
            }
        }
        else
        {
            <div>No calendar events found</div>
        }
    }
    else
    {
        <a class="btn btn-primary btn-large" asp-area="MicrosoftIdentity" asp-controller="Account" asp-action="SignIn">Click here to sign in</a>
    }

</div>

NETCoreMVCwithMSGraph/Views/Home/Index.cshtml
@model NETCoreMVCwithMSGraph.Models.Profile
@{
    ViewData["Title"] = "Home Page";
}
<div>
    <h1>User Profile</h1>
    <br />
    @if ((User.Identity?.IsAuthenticated == true))
    {
        <h4>
            @if (Model.UserPhoto != null)
            {
                <img src="data:image/jpeg;base64, @Model.UserPhoto" class="user-photo nav-profile-photo rounded-circle align-self-center mr-2" />
            }
            Welcome @Model.UserDisplayName!
        </h4>
    }
    else
    {
        <a class="btn btn-primary btn-large" href="https://localhost:7004/signin-oidc">Click here to sign in</a>
    }
</div>

NETCoreMVCwithMSGraph/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NETCoreMVCwithMSGraph</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NETCoreMVCwithMSGraph.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
       
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NET Core MVC with MS Graph</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
              
                <div class="navbar-collapse collapse d-sm-inline-flex">
                  
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Email" asp-action="Index">Email</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Calendar" asp-action="Index">Calendar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="ToDoTask" asp-action="Index">To Do</a>
                        </li>
                    </ul>
                   
                </div>
                <div class="justify-content-end">
                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - NET Core MVC with MS Graph - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

NETCoreMVCwithMSGraph/Views/ToDoTask/Index.cshtml
@model NETCoreMVCwithMSGraph.Models.ToDoTaskModel
@{
    ViewData["Title"] = "To Do Task List";
}

<div>
    <h1>To Do Task List</h1>
    @if ((User.Identity?.IsAuthenticated == true))
    {
        if (Model.TaskLists != null && Model.TaskLists.Any())
        {
            @foreach (var tasks in Model.TaskLists)
            {

                <div class="card" style="width: 50rem;">
                    <div class="card-body">
                        <h5 class="card-title">
                            @tasks.DisplayName

                        </h5>
                      
                    </div>
                </div>
                <br />

            }

        }
        else
        {
            <div>No Tasks found</div>
        }
    }
    else
    {
        <a class="btn btn-primary btn-large" asp-area="MicrosoftIdentity" asp-controller="Account" asp-action="SignIn">Click here to sign in</a>
    }


</div>